### ISSUE TITLE
no debounce for Wio Terminal buttons

### ISSUE THREAD

**Issue by mplogas** [shnam7/ardukit#1]
**Issue**: I'm trying to get Ardukit to work with my WioTerminal. However, I have not been able to get the buttons to work

**Expected result**: Button pressed/released gives a serial message
**Observed result:** The button pressed event is triggered during setup and not anymore after that. No release event is fired at all. I have played with the sensitivity overload without any luck. 
**Additional info:** When reading the button value manually (``` digitalRead(WIO_KEY_A) == LOW ```), the event is recognized.

**Code:** 
```
#include "rpcWiFi.h"
#include <ardukit.h>

adk::Button bFavA(WIO_KEY_A, INPUT_PULLUP);
 
void setup() {
    Serial.begin(115200);
    while(!Serial);
    Serial.printf("RTL8720 Firmware Version: %s", rpc_system_version());

    bFavA.enable();
    bFavA.on("press", onButtonFavA);
    bFavA.on("release", onButtonFavA);
}
 
void loop() {
      adk::run();
}

void onButtonFavA(adk::EventEmitter::event &e)
{
    Serial.printf("button: %s", e.name);
};
```

**Serial Log:**
```
14:35:30.136 -> RTL8720 Firmware Version: 2.1.2
14:35:30.136 -> button: press
```

**Further links:** 
Wio Terminal overview: https://wiki.seeedstudio.com/Wio-Terminal-Getting-Started/
Wio Terminal buttons: https://wiki.seeedstudio.com/Wio-Terminal-Buttons/

**Comment by shnam7** [comment]
I think you code would fail to compile because onButtonFavA is not declared before it is used in setup().
Did you check if the button example included in ardukit works correctly in your environment?
I tested it again  with Uno board, and it is working fine.

**Comment by mplogas** [comment]
It compiles just fine and the action is called once during start/assignment.

**Comment by shnam7** [comment]
Does the button demo (https://github.com/shnam7/ardukit/blob/master/examples/button/button.ino) work as expected? It should emit 'press' event and 'release' event only once whenever the button is pressed and released.

And, would you try your code with button type INPUT instead of INPUT_PULLUP?

> adk::Button bFavA(WIO_KEY_A, **PULLUP**);

**Comment by mplogas** [comment]
> Does the button demo (https://github.com/shnam7/ardukit/blob/master/examples/button/button.ino) work as expected? It should emit 'press' event and 'release' event only once whenever the button is pressed and released.

No, it's not. The event is only triggered once during start and is never firing on button press. That is consistent with my reported issue.

> And, would you try your code with button type INPUT instead of INPUT_PULLUP?

I tried this, but the event isn't firing at all, not even during start.

**Comment by shnam7** [comment]
If the events are not triggered whenever the button is pressed, timer logic may not be working, which is periodically calling button::scan() function.
I created a dev branch with debug  messages in button::scan() function to check on this.
https://github.com/shnam7/ardukit/blob/dev/src/gbutton.cpp

Would you checkout this branch and do the following two things:
- Execute button example again and capture first 5~10 lines of the serial output. It should display repeating debug messages
- Execute a timer example https://github.com/shnam7/ardukit/blob/dev/examples/timer-01/timer-01.ino and see if it is working (repeatedly printing changing brightness values)

**Comment by mplogas** [comment]
Hi @shnam7,
thanks for your work. 

this is the serial output from the button sample right from the start. pressing a button does nothing.
```
22:37:29.669 -> scan: sensitiviey=2, delta=1 cur==2 is_pressed=1
22:37:29.716 -> scan: sensitiviey=2, delta=1 cur==2 is_pressed=1
22:37:29.716 -> scan: sensitiviey=2, delta=1 cur==2 is_pressed=1
22:37:29.716 -> scan: sensitiviey=2, delta=1 cur==2 is_pressed=1
22:37:29.762 -> scan: sensitiviey=2, delta=1 cur==2 is_pressed=1
22:37:29.762 -> scan: sensitiviey=2, delta=1 cur==2 is_pressed=1
22:37:29.809 -> scan: sensitiviey=2, delta=1 cur==2 is_pressed=1
22:37:29.809 -> scan: sensitiviey=2, delta=1 cur==2 is_pressed=1
22:37:29.855 -> scan: sensitiviey=2, delta=1 cur==2 is_pressed=1
22:37:29.855 -> scan: sensitiviey=2, delta=1 cur==2 is_pressed=1
22:37:29.855 -> scan: sensitiviey=2, delta=1 cur==2 is_pressed=1
22:37:29.902 -> scan: sensitiviey=2, delta=1 cur==2 is_pressed=1
22:37:29.902 -> scan: sensitiviey=2, delta=1 cur==2 is_pressed=1
```

The timer example is working as expected and so are your tasks samples.

```
22:44:00.692 -> LED brightness: 30
22:44:00.692 -> LED brightness: 35
22:44:00.692 -> LED brightness: 40
...
2:44:01.112 -> LED brightness: 245
22:44:01.112 -> LED brightness: 250
22:44:01.112 -> LED brightness: 255
22:44:01.112 -> LED brightness: 250
22:44:01.158 -> LED brightness: 245
...
22:44:01.626 -> LED brightness: 10
22:44:01.626 -> LED brightness: 5
22:44:01.626 -> LED brightness: 0
```

**Comment by shnam7** [comment]
Hi @mplogas
Here are some points you need to check:
- 'delta' should be -1 when the button is not pressed. Your result shows it as 1, so please try to change io_type to INPUT or INPUT_PULLUP until you have -1 for the 'delta', when the button is not pressed.
- 'cur' starts from 0 and increases up to 2 (sensitivity) or decreased down to 0 by the 'delta'. Please catch the points that the 'cur' changes from 0 to 2 or 2 to 0. You'd be able to see that at the start of the program or whenever the key is pressed or released.
- Please make sure the 'delta' changes (1 or -1) whenever the button is pressed. Or, you'd need to check if the digitalRead() value changes whenever the button is pressed.

Please let me know your observation.

**Comment by mplogas** [comment]
@shnam7 FYI, I will be traveling for a few days. I'll implement you suggestions early next week and get back to you.

**Comment by shnam7** [comment]
No worries. Have a safe trip!

**Comment by shnam7** [comment]
Hi @mplogas
Maybe you have found the answer from the test points above.
Let me know the test result if you still experiencing the problem.
Or, let me close the issue now.
Thanks

**Comment by mplogas** [comment]
Hi @shnam7,
sorry for the late reply. Real life got in the way :)

Anyway, I followed your suggestions using your base button sample:

> 'delta' should be -1 when the button is not pressed. Your result shows it as 1, so please try to change io_type to INPUT or INPUT_PULLUP until you have -1 for the 'delta', when the button is not pressed.

When changing this to ```INPUT``` the delta turns -1. (FYI, according to the [Wio Terminal documentation](https://wiki.seeedstudio.com/Wio-Terminal-Buttons/), the button should be initialized with ```INPUT_PULLUP```)

> 'cur' starts from 0 and increases up to 2 (sensitivity) or decreased down to 0 by the 'delta'. Please catch the points that the 'cur' changes from 0 to 2 or 2 to 0. You'd be able to see that at the start of the program or whenever the key is pressed or released.

> Please make sure the 'delta' changes (1 or -1) whenever the button is pressed. Or, you'd need to check if the digitalRead() value changes whenever the button is pressed.

The button press event is never registered. The button works in the Wio Terminal documentation sample and when [using the AceButtons lib](https://github.com/mplogas/SensorTerminal/blob/master/src/main.cpp)

**Comment by shnam7** [comment]
Hi @mplogas
Would you try again with latest updates of the dev branch, setting the io_type to INPUT_PULLUP?

**Comment by shnam7** [comment]
Hi @mplogas
ardukit v1.1.0 is released, which has some improvement in button class supporting internal pull-up and external pull-up/pull-down register options with more flexibility.
Maybe this version could resolve your issue and you may want to try it.

**Comment by shnam7** [comment]
This issue is closed having no further feedback from the issue opener.
