### ISSUE TITLE
Example for List

### ISSUE THREAD

**Issue by adborden** [shnam7/ardukit#2]
Hello, I'm having trouble using the List data structure.

This example fails to compile with error. It seems a class using `List` needs to provide conversion or inherit from `Linkable`?

> /home/adborden/Arduino/libraries/ardukit/src/glist.h: In instantiation of 'void adk::List<T>::append(T*) [with T = Pixel]':
/home/adborden/Arduino/circuit_playground/circuit_playground.ino:323:16:   required from here
/home/adborden/Arduino/libraries/ardukit/src/glist.h:46:44: error: no matching function for call to 'adk::List<Pixel>::append(Pixel*&)'
     void append(T *node) { Linkable::append(node); };
                            ~~~~~~~~~~~~~~~~^~~~~~
/home/adborden/Arduino/libraries/ardukit/src/glist.h:24:10: note: candidate: void adk::Linkable::append(adk::Linkable*)
     void append(Linkable *node);
          ^~~~~~
/home/adborden/Arduino/libraries/ardukit/src/glist.h:24:10: note:   no known conversion for argument 1 from 'Pixel*' to 'adk::Linkable*'
exit status 1

```c++
using namespace adk;

class Pixel {};

void setup() {
  List<Pixel> list;
  Pixel *p = new Pixel();
  list.append(p);
}
```

**Comment by shnam7** [comment]
Yes, the Pixel class should inherit from Linkable.
You can find general examples from https://github.com/shnam7/opengcl, which is the original library that ardukit is based on.

List example: https://github.com/shnam7/opengcl/blob/master/samples/ex-list.cpp

**Comment by adborden** [comment]
Thanks!

Is the list stored in reverse? The iterator reports items backwards from what I would expect:

```c++
class LinkableInt : public Linkable {
  int m_i;
public:
    LinkableInt(int i) : m_i(i) {};
    int get() { return m_i; };
};


void loop() {

  Serial.println("reset");
  List<LinkableInt> list;

  for (int i = 0; i < 10; i++) {
    list.append(new LinkableInt(i));
  }

  Serial.print("list: ");
  Serial.println(list.length());

  for (auto i = list.begin(); i != list.end(); i++) {

      Serial.print("loop1: ");
      Serial.print(list.length());
      Serial.print(" ");
      Serial.println(i->get());
  }

  Serial.println();
  Serial.println();
}
```

output: 
```
reset
list: 10
loop1: 10 9
loop1: 10 8
loop1: 10 7
loop1: 10 6
loop1: 10 5
loop1: 10 4
loop1: 10 3
loop1: 10 2
loop1: 10 1
loop1: 10 0

```

**Comment by shnam7** [comment]
Found error in glist::append() implementation, and v1.1.1 released with the fix.
Thanks for your feedback.

**Comment by shnam7** [comment]
Closing the issue having no further questions.
